# Generated by Django 3.1.4 on 2022-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='database_name',
            field=models.ManyToManyField(to='manager.DataBase'),
        ),
    ]
