# Generated by Django 3.1.4 on 2022-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220204_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_name',
            field=models.ManyToManyField(to='manager.Framework'),
        ),
    ]
