# Generated by Django 3.1.4 on 2022-02-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20220204_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='toll_name',
            new_name='tool_name',
        ),
    ]
