# Generated by Django 3.1.4 on 2022-02-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20220204_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
