# Generated by Django 3.1.4 on 2022-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220204_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='detail',
            new_name='company_detail',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='my_detail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
