# Generated by Django 3.1.4 on 2022-02-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20220204_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlanguage',
            name='language_name',
        ),
        migrations.AddField(
            model_name='projectlanguage',
            name='language_name',
            field=models.ManyToManyField(to='manager.Planguage'),
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='projecttool',
            name='tool_name',
            field=models.ManyToManyField(to='manager.Dtool'),
        ),
        migrations.CreateModel(
            name='ProjectFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.ManyToManyField(to='manager.Framework')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.ManyToManyField(to='manager.DataBase')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.project')),
            ],
        ),
    ]
