# Generated by Django 3.1.4 on 2022-02-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20220204_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planguage',
            old_name='language_name',
            new_name='name',
        ),
    ]
