# Generated by Django 3.1.4 on 2022-02-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20220204_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.DeleteModel(
            name='Heding',
        ),
        migrations.DeleteModel(
            name='Navabr',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='database_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='database',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtool',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framework',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planguage',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
    ]
