# Generated by Django 3.1.4 on 2022-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20220207_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='dtool',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='planguage',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='database_name',
            field=models.ManyToManyField(to='manager.DataBase'),
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_name',
            field=models.ManyToManyField(to='manager.Framework'),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_name',
            field=models.ManyToManyField(to='manager.Planguage'),
        ),
        migrations.AddField(
            model_name='skills',
            name='tool_name',
            field=models.ManyToManyField(to='manager.Dtool'),
        ),
    ]
