# Generated by Django 3.1.4 on 2022-02-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20220207_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='database_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='tool_name',
        ),
    ]
