# Generated by Django 3.1.4 on 2022-02-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20220207_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtool',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framework',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planguage',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.skills'),
            preserve_default=False,
        ),
    ]
