# Generated by Django 3.1.4 on 2022-02-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20220207_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(default=0, upload_to='skills'),
            preserve_default=False,
        ),
    ]
